# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='tt',
            new_name='place',
        ),
    ]
